name: Execute Make Command with Env Variables

permissions:
  id-token: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-make-command:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SECRETS }}'

      - id: 'check-auth'
        name: 'Verify Authentication and List Services'
        run: |-
            gcloud auth list
            gcloud services list
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Run Make Command
        env:
          START_DATE: ${{ github.event.inputs.START_DATE }}
          END_DATE: ${{ github.event.inputs.END_DATE }}
          PYPI_PROJECT: ${{ github.event.inputs.PYPI_PROJECT }}
          TABLE_NAME: ${{ github.event.inputs.TABLE_NAME }}
          S3_PATH: ${{ github.event.inputs.S3_PATH }}
          AWS_PROFILE: ${{ github.event.inputs.AWS_PROFILE }}
          GCP_PROJECT: ${{ github.event.inputs.GCP_PROJECT }}
          TIMESTAMP_COLUMN: ${{ github.event.inputs.TIMESTAMP_COLUMN }}
          DESTINATION: ${{ github.event.inputs.DESTINATION }}
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
        run: |
          make pypi-ingest
