name: Execute Make Command with Env Variables

permissions:
  id-token: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-make-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SECRETS }}'

      - name: Pull latest Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Run Make Command
        env:
          START_DATE: 2023-01-01
          END_DATE: 2023-02-01
          PYPI_PROJECT: duckdb
          TABLE_NAME: pypi_file_downloads
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }} 
          TIMESTAMP_COLUMN: timestamp
          DESTINATION: md
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
          AWS_PROFILE: None
          S3_PATH: None
        run: |
          make pypi-ingest DOCKER=true
